wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240112_031222-ewk54s4z
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run zany-valley-90
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/ewk54s4z
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 140, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 96, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 89, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_191222-fonjvtd7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run golden-dragon-91
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/fonjvtd7
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 140, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 96, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 89, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_191222-ctcytco6
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run good-grass-92
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/ctcytco6
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 140, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 96, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_no_lagrange.py", line 89, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: üöÄ View run zany-valley-90 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/ewk54s4z
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240112_031222-ewk54s4z/logs
wandb: üöÄ View run good-grass-92 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/ctcytco6
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_191222-ctcytco6/logs
wandb: üöÄ View run golden-dragon-91 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/fonjvtd7
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_191222-fonjvtd7/logs
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: dqn.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
