False
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/tests/PPOL_New/train_ppol_image_cnn.py", line 25, in <module>
    print(th.cuda.current_device())  # Prints the index of the current CUDA device
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
False
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/tests/PPOL_New/train_ppol_image_cnn.py", line 25, in <module>
    print(th.cuda.current_device())  # Prints the index of the current CUDA device
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: rlhf.ist.berkeley.edu: task 0: Exited with exit code 1
False
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/tests/PPOL_New/train_ppol_image_cnn.py", line 25, in <module>
    print(th.cuda.current_device())  # Prints the index of the current CUDA device
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
srun: error: sac.ist.berkeley.edu: task 0: Exited with exit code 1
